# Generated by Django 5.2.7 on 2025-12-03 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_attendance_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
