# Generated by Django 5.2.7 on 2025-12-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_day', models.DecimalField(decimal_places=2, default=0, help_text='Total hours for this day', max_digits=6)),
                ('total_hours_week', models.DecimalField(decimal_places=2, default=0, help_text='Total hours for the week (Mon-Sun)', max_digits=7)),
                ('total_hours_fortnight', models.DecimalField(decimal_places=2, default=0, help_text='Total hours for the fortnight (14 days)', max_digits=8)),
                ('total_hours_month', models.DecimalField(decimal_places=2, default=0, help_text='Total hours for the calendar month', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Total Attendance',
                'verbose_name_plural': 'Total Attendance Records',
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of attendance for this day', null=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance__user_id_c01e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', '-date'], name='attendance__user_id_4791a1_idx'),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='total_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='totalattendance',
            index=models.Index(fields=['user', 'updated_at'], name='attendance__user_id_e26560_idx'),
        ),
    ]
