# Generated by Django 5.2.7 on 2025-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_totalattendance_alter_attendance_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalattendance',
            old_name='total_hours_day',
            new_name='total_hours',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_hours_fortnight',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_hours_month',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_hours_week',
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for this day', max_digits=6),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_fortnight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for the fortnight (14 days)', max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_month',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for the calendar month', max_digits=9),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_week',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for the week (Mon-Sun)', max_digits=7),
        ),
    ]
