# Generated by Django 5.2.7 on 2025-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_total_hours_day_totalattendance_total_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestatus',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_day',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_fortnight',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_month',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='total_week',
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='half_day_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='payable_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_payable_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payable days', max_digits=8),
        ),
        migrations.AddField(
            model_name='totalattendance',
            name='total_payable_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payable hours', max_digits=10),
        ),
    ]
