# Generated by Django 5.2.7 on 2025-12-11 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendancestatus_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='totalattendance',
            name='attendance__user_id_e26560_idx',
        ),
        migrations.RemoveField(
            model_name='totalattendance',
            name='payable_days',
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total absent days', max_digits=8),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='half_day_count',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total half days', max_digits=8),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total paid leave days', max_digits=8),
        ),
        migrations.AlterField(
            model_name='totalattendance',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total present days', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='totalattendance',
            index=models.Index(fields=['user'], name='attendance__user_id_c58c73_idx'),
        ),
        migrations.AddIndex(
            model_name='totalattendance',
            index=models.Index(fields=['updated_at'], name='attendance__updated_d1f983_idx'),
        ),
    ]
