# Generated by Django 5.2.7 on 2025-12-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_totalattendance_attendance__user_id_e26560_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalAttendance',
        ),
    ]
