# Generated by Django 5.2.7 on 2025-12-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_delete_totalattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestatus',
            name='owner',
            field=models.ForeignKey(default=2, limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_statuses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
