# Generated by Django 5.2.7 on 2025-12-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancestatus_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestatus',
            name='owner',
        ),
    ]
