# Generated by Django 5.2.7 on 2025-12-31 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancestatus_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_attendance_days', models.IntegerField(default=0)),
                ('total_payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_absent_days', models.IntegerField(default=0)),
                ('total_leave_days', models.IntegerField(default=0)),
                ('salary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('final_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='attendance__user_id_053df4_idx'), models.Index(fields=['user', 'updated_at'], name='attendance__user_id_46187d_idx')],
                'unique_together': {('user', 'start_date', 'end_date')},
            },
        ),
    ]
