# Generated by Django 5.2.7 on 2025-12-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='total_absent_days',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='total_attendance_days',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='total_leave_days',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='half_day_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='total_payable_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='unpaid_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='weekly_Offs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
