# Generated by Django 5.2.7 on 2026-01-02 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('emergency_contact_2', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')])),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('present_health_condition', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=20, null=True)),
                ('id_proof', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving-license', 'Driving License'), ('voter-id', 'Voter ID'), ('other', 'Other')], max_length=20)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('patient_documents', models.FileField(help_text='Upload related document', upload_to='patient_documents/')),
                ('education_qualifications', models.TextField(blank=True, null=True)),
                ('earlier_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_retirement', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('net-banking', 'Net Banking'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('bank-transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(help_text='User who registered this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['email'], name='booking_pat_email_1f635d_idx'), models.Index(fields=['phone'], name='booking_pat_phone_c8ea6f_idx'), models.Index(fields=['-registration_date'], name='booking_pat_registr_c3228f_idx'), models.Index(fields=['registered_by'], name='booking_pat_registe_fdd519_idx')],
            },
        ),
    ]
