# Generated by Django 5.2.7 on 2026-01-21 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetransaction',
            old_name='due_amount',
            new_name='remain_amount',
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoicetransaction',
            name='total_bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='invoice_for',
            field=models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service')], default='VENUE', help_text='VENUE: venue + services | SERVICE: standalone services', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='service_bookings',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='booking.bookingservice'),
        ),
    ]
