# Generated by Django 5.2.7 on 2025-10-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0002_location_remove_venue_address_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
