# Generated by Django 5.2.7 on 2025-10-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0003_venue_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
