# Generated by Django 5.2.7 on 2025-11-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhierarchy',
            options={'verbose_name': 'User Hierarchy', 'verbose_name_plural': 'User Hierarchies'},
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='hierarchy_level',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='parent_user',
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Hierarchy level: 0=Owner, 1=Manager, 2=Staff, etc.'),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Immediate parent user (Owner or Manager).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager for staff (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='owner',
            field=models.ForeignKey(help_text='Top-level owner for this user.', limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='user',
            field=models.OneToOneField(help_text='The user this hierarchy record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to=settings.AUTH_USER_MODEL),
        ),
    ]
