# Generated by Django 5.2.7 on 2025-11-11 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhierarchy',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userhierarchy',
            name='manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Virtual', 'Virtual'), ('PPO', 'PPO'), ('Vendor', 'Vendor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='order_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qc_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='band',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhierarchy',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='owner',
            field=models.ForeignKey(help_text='Top-level owner for this user hierarchy.', limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Immediate supervisor (owner or manager).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='user',
            field=models.OneToOneField(help_text='User associated with this hierarchy record.', on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to=settings.AUTH_USER_MODEL),
        ),
    ]
