# Generated by Django 5.2.7 on 2025-11-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vsreownerprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsrestaffprofile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.vsremanagerprofile'),
        ),
    ]
