# Generated by Django 5.2.7 on 2025-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userhierarchy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhierarchy',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Hierarchy depth (Owner=0, Manager=1, etc.)'),
        ),
    ]
