# Generated by Django 5.2.7 on 2025-11-13 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
