# Generated by Django 5.2.7 on 2025-11-13 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 13), null=True),
        ),
    ]
