# Generated by Django 5.2.7 on 2026-01-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20)),
                ('change_type', models.CharField(choices=[('BASE_SALARY', 'Base Salary'), ('INCREMENT', 'Increment'), ('ADVANCE', 'Advance'), ('LOAN', 'Loan')], default='BASE_SALARY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('change_type', 'BASE_SALARY')), fields=('user',), name='unique_base_salary_per_user')],
                'unique_together': {('user', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_period_start', models.DateField()),
                ('payment_period_end', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VSRE_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_paid', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_period_start'],
                'indexes': [models.Index(fields=['receiver', '-processed_at'], name='payroll_sal_receive_a97019_idx'), models.Index(fields=['status', 'created_at'], name='payroll_sal_status_cbd8dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_payable_amount__gt', 0)), name='total_payable_amount_positive'), models.CheckConstraint(condition=models.Q(('payment_period_end__gte', models.F('payment_period_start'))), name='valid_salary_period')],
            },
        ),
    ]
